import "./globals.css";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import Providers from "./providers";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"

export const metadata: Metadata = {
  title: "REKr Forum",
  description: "Generated by create rekr forum",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
          <Analytics />
        </Providers>
      </body>
    </html>
  );
}
